### ISSUE TITLE
More usage examples

### ISSUE THREAD

**Issue by msurguy** [Apercu/react-native-zeroconf#11]
Hello! 

Sorry if this sounds silly. 

I would like to ask if there is a way to add more examples of using this library, specifically how to retrieve objects retrieved on `resolved` function and whether I should do `zeroconf.getServices();` inside of on 'start' listener. 

Thanks!

**Comment by Apercu** [comment]
Hi,

If you call `getServices` directly in the start listener, you'll simply get nothing, since no service would have been resolved yet. This method is useful when you want to get the full list of resolved services periodically or manually.

If you want to get the services immediately after they are resolved, you should add the resolved listener that pass you the new service that have been resolved. You could also call the `getServices` method in here to get the updated list.

You could have a look to a real example at my [remote application](https://github.com/Apercu/furtive-app) (sorry the code is not perfect, first rn project), and specifically at [this file](https://github.com/Apercu/furtive-app/blob/develop/src/pages/MainPage.js) where all the fun occurs.
Careful though, this is an old API of RNZeroconf, and it has drastically changed now, but this could give you an idea of what you should do.

Tell me if that didn't help you, and I can think of adding an example to this ;)

**Comment by Apercu** [comment]
@msurguy Hi again! If you don't have any further questions, I'm gonna close this. If you still think examples are needed, tell me and I'll do it!
